# Generated by Django 5.1.5 on 2025-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیامهای تماس'},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار پاسخ'), ('replied', 'پاسخ داده شده')], default='pending', max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
    ]
