# Generated by Django 4.2.17 on 2024-12-16 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('description', models.TextField(verbose_name='محتوا')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر مقاله')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_special', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='وید\u200d\u200dیو')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articless', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی\u200cپی')),
            ],
        ),
        migrations.CreateModel(
            name='Vakil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='شماره پروانه')),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر وکیل')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Riyasat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True, verbose_name='نقش')),
                ('vakil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vakils', to='home.vakil', verbose_name='وکیل')),
            ],
        ),
        migrations.CreateModel(
            name='ComisionVarzeshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raees', models.BooleanField(default=False)),
                ('aaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vakil')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('raees', models.BooleanField(default=False)),
                ('vakils', models.ManyToManyField(blank=True, null=True, related_name='comisions', to='home.vakil')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='articleimages/')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='home.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='home.ArticleHit', to='home.ipaddress', verbose_name='بازدیدها'),
        ),
    ]
