# Generated by Django 5.1.4 on 2024-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='vakils',
            field=models.ManyToManyField(related_name='comisions', to='home.vakil'),
        ),
    ]
