# Generated by Django 5.1.4 on 2025-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article_files/'),
        ),
    ]
