# Generated by Django 5.1.4 on 2025-01-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_articleimage_name_alter_articlefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='name',
        ),
        migrations.AddField(
            model_name='articlefile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
