# Generated by Django 5.1.5 on 2025-02-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_articleimage_name_articlefile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='raees',
        ),
        migrations.AddField(
            model_name='comision',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_comisions', to='home.vakil'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='vakils',
            field=models.ManyToManyField(related_name='comisions', to='home.vakil'),
        ),
        migrations.DeleteModel(
            name='ComisionVarzeshi',
        ),
    ]
