# Generated by Django 5.1.5 on 2025-02-05 20:04

import autoslug.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True, verbose_name='آدرس مقاله'),
        ),
    ]
