# Generated by Django 5.1.5 on 2025-02-05 20:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_article_description_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='title', unique=True, verbose_name='آدرس مقاله'),
        ),
    ]
