# Generated by Django 5.1.5 on 2025-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_riyasat_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakil',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='اسلاگ شهر'),
        ),
        migrations.AlterField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام فارسی شهر'),
        ),
    ]
