# Generated by Django 5.1.5 on 2025-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_vakil_city_slug_alter_vakil_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakil',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='اسلاگ شهر'),
        ),
    ]
