# Generated by Django 5.1.5 on 2025-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_vakil_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakil',
            name='city_slug',
        ),
        migrations.AlterField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر'),
        ),
    ]
