# Generated by Django 5.1.5 on 2025-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_vakil_city_slug_alter_vakil_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakil',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='اسلاگ شهر'),
        ),
    ]
