# Generated by Django 5.1.5 on 2025-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_vakil_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, choices=[('همدان', 'همدان'), ('کبودراهنگ', 'کبودراهنگ'), ('ملایر', 'ملایر')], max_length=150, null=True, verbose_name='شهر'),
        ),
    ]
