# Generated by Django 5.1.5 on 2025-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_vakil_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, choices=[('همدان', 'hamedan'), ('کبودراهنگ', 'کبودراهنگ'), ('ملایر', 'ملایر'), ('ملایر', 'ملایر'), ('ملایر', 'ملایر'), ('ملایر', 'ملایر'), ('ملایر', 'ملایر'), ('ملایر', 'ملایر')], max_length=150, null=True, verbose_name='شهر'),
        ),
    ]
