# Generated by Django 5.1.5 on 2025-02-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_vakil_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, choices=[('همدان', 'همدان'), ('کبودراهنگ', 'کبودراهنگ'), ('ملایر', 'ملایر'), ('اسدآباد', 'اسدآباد'), ('نهاوند', 'نهاوند'), ('تویسرکان', 'تویسرکان'), ('رزن', 'رزن'), ('درگزین', 'درگزین'), ('بهار', 'بهار'), ('فامنین', 'فامنین')], max_length=150, null=True, verbose_name='شهر'),
        ),
    ]
