# Generated by Django 5.1.5 on 2025-04-19 14:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_vakil_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, max_length=100, populate_from='title', unique=True),
        ),
    ]
