# Generated by Django 5.1.5 on 2025-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_article_author_alter_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='تصویر مقاله'),
        ),
    ]
