# Generated by Django 5.1.5 on 2025-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakil',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='vakil',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس دفتر'),
        ),
    ]
