# Generated by Django 5.1.5 on 2025-05-21 08:19

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_vakil_mobile_vakil_phone'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='برچسب\u200cها را با کاما جدا کنید.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
    ]
