# Generated by Django 5.1.5 on 2025-05-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='images',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.article'),
        ),
    ]
