# Generated by Django 5.1.5 on 2025-05-24 06:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_articleimage_images_articleimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا'),
        ),
    ]
