# Generated by Django 5.1.5 on 2025-05-24 06:47

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
