# Generated by Django 5.1.5 on 2025-05-24 07:53

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakil',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا'),
        ),
    ]
