# Generated by Django 5.1.5 on 2025-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_vakil_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakil',
            name='date',
        ),
        migrations.AddField(
            model_name='vakil',
            name='day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='vakil',
            name='month',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='vakil',
            name='year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
